apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  
  policy.csv: |
    # Deployers peuvent synchroniser
    p, role:deployer, applications, sync, */*, allow
    p, role:deployer, applications, get, */*, allow
    p, role:deployer, applications, override, */*, allow
    
    # Developers ont lecture seule + logs
    p, role:developer, applications, get, */*, allow
    p, role:developer, logs, get, */*, allow
    p, role:developer, projects, get, *, allow
    
    # Admins ont tous les droits
    p, role:admin, *, *, *, allow
    
    # Alice est deployer
    g, alice, role:deployer
    
    # Bob est developer
    g, bob, role:developer